### PR TITLE
Redirect site to dapp.tools

### PR DESCRIPTION
**Pull request by transmissions11**
also removed the ACS link as it seems to be pretty dead but left it as a comment in case someone wants to restore it

### CODE REVIEW

**Comment by d-xo** [comment]
hmmmmm yeah this website is pretty dead, I think we're probably just going to redirect it to dapp.tools once we figure out who controls the domain....

**Comment by transmissions11** [comment]
> hmmmmm yeah this website is pretty dead, I think we're probably just going to redirect it to dapp.tools once we figure out who controls the domain....

gotcha. i mean it looks like it's properly hooked up to github pages? i could update the index.html to use a meta tag to redirect to dapptools in the meantime

**Comment by d-xo** [comment]
oh yeah, that's a very good idea!

**Comment by transmissions11** [comment]
> oh yeah, that's a very good idea!

dope, done!

**Review by d-xo — APPROVED** [review]

**Pull request merged**
